### PR TITLE
stelle configuration for development and production

### PR DESCRIPTION
**Pull request by MARCROCK22**

### CODE REVIEW

**Comment by EvilG-MC** [comment]
Thank you gato! But I may have a better way to do this.

**Comment by MARCROCK22** [comment]
I don't think so! This is the only one way to do it!
In programming there is only one way to do certain things.

**Comment by EvilG-MC** [comment]
> I don't think so! This is the only one way to do it! In programming there is only one way to do certain things.

Sleep gato, sleep.🐐

**Comment by MARCROCK22** [comment]
🐢

**Pull request closed without merging**
